version: '3'

services:
    serpioctopus:
        build:
            context: .
        container_name: serpioctopus
        image: octopus/serpioctopus
        volumes:
            - ./app/shared:/home/node/shared
        network_mode: host
        restart: always